ServerPort: ":8080"
PkgFileDir: "public/programs"
LogConfig:
  Level: "info"
  Format: "console"
  File: "app.log"
  MaxSize: 10
  MaxAge: 7
  Compress: true
  Filename: "app.log"
  ResponseSize: 1000
MySQL:
  Host: "localhost"
  Port: 3306
  Username: "root"
  Password: "root"
  Database: "updater"
